eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        preferIpAddress: true
info:
    app:
        version: 1.0
management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8072
spring:
    application:
        name: gateway-service
    boot:
        admin:
            client:
                instance:
                    name: gateway-service
                url: http://localhost:9105
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/auth/realms/gainde-realm
    zipkin:
        baseUrl: http://localhost:9411/
        service:
            name: gateway-service
