eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://discovery-service:8070/eureka/
    instance:
        preferIpAddress: true
info:
    app:
        version: 1.0
management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8072
spring:
    application:
        name: gateway-service
    boot:
        admin:
            client:
                instance:
                    name: gateway-service
                url: http://admin-service:9105
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
